tokenizer:
  model_name: t5-base
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  id: meteor
  args:
    shaping_fn: "common_gen_repeat_penalty"



datapool:
  id: commongen
  args:
    concept_end_token: '.'
    concept_separator_token: ' '
    prefix: "generate a sentence with: "


env:
  n_envs: 1
  model_name: t5-base
  model_type: seq2seq
  args:
    max_length: 20
    max_prompt_length: 50
    n_turns: 1
    device: cpu
    dataset_path: /homedtcl/mmahaut/projects/llm2llm/data/mindless_dataset_randomized_train.txt


alg:
  id: ppo
  args:
    n_steps: 256
    batch_size: 64
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 5
    ent_coef: 0.01
  kl_div:
    coeff: 0.001
    target_kl: 2.0
  policy:
    id: causal_lm_actor_critic_policy
    args:
      model_name: gpt2-large
      apply_model_parallel: True
      prompt_truncation_side: "right"
      generation_kwargs:
        do_sample: True
        top_k: 0
        min_length: 5
        max_new_tokens: 20
    
train_evaluation:
  eval_batch_size: 20
  n_iters: 200
  eval_every: 20
  save_every: 1
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
    - id: bert_score
      args:
        language: en
    - id: diversity
      args: {}
  generation_kwargs:
    num_beams: 5
    min_length: 5
    max_new_tokens: 20

